---
development:
  DB_FILENAME: db/local/dev.db
  spotify_Client_ID: provision_spotify_api_ID
  spotify_Client_secret: provision_spotify_api_secret
  API_HOST: http://localhost:9090
  REDIS_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  ADD_PODCAST_INFO_QUEUE: transound-add-podcast-development.fifo
  ADD_PODCAST_INFO_QUEUE_URL: <set by AWS>
  REPORT_QUEUE: transound-report-development
  REPORT_QUEUE_URL: <set by AWS>

test:
  DB_FILENAME: db/local/test.db
  spotify_Client_ID: provision_spotify_api_ID
  spotify_Client_secret: provision_spotify_api_secret
  API_HOST: http://localhost:9090
  REDIS_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  ADD_PODCAST_INFO_QUEUE: transound-add-podcast-test.fifo
  ADD_PODCAST_INFO_QUEUE_URL: <set by AWS>  
  REPORT_QUEUE: transound-report-development
  REPORT_QUEUE_URL: <set by AWS>

production:
  # - assign DATABASE_URL in production
  spotify_Client_ID: provision_spotify_api_ID
  spotify_Client_secret: provision_spotify_api_secret
  API_HOST: api-host-on-heroku
  REDIS_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  ADD_PODCAST_INFO_QUEUE: transound-add-podcast-development.fifo
  ADD_PODCAST_INFO_QUEUE_URL: <set by AWS>
  REPORT_QUEUE: transound-report-development
  REPORT_QUEUE_URL: <set by AWS>
